version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
  backend:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - redis