# Generated by Django 4.2.6 on 2023-10-23 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'gif', 'ico', 'jp2', 'jpeg', 'png', 'psd', 'tiff', 'webp', '3g2', '3gp', 'asf', 'avi', 'flv', 'm4v', 'mkv', 'mov', 'mp4', 'mpg', 'ogv', 'swf', 'vob', 'webm', 'wmv', 'doc', 'docx', 'epub', 'key', 'numbers', 'odp', 'ods', 'odt', 'pages', 'pdf', 'pps', 'ppt', 'pptx', 'rtf', 'xls', 'xlsx', 'xml', '7z', 'dmg', 'gz', 'iso', 'rar', 'tar.z', 'zip'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала загрузки')),
                ('processed', models.BooleanField(default=False, verbose_name='Состояние процесса')),
            ],
        ),
    ]
