# Generated by Django 4.2.6 on 2023-10-24 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'gif', 'ico', 'jp2', 'jpeg', 'jpg', 'png', 'psd', 'tiff', 'webp', '3g2', '3gp', 'asf', 'avi', 'flv', 'm4v', 'mkv', 'mov', 'mp4', 'mpg', 'ogv', 'swf', 'vob', 'webm', 'wmv', 'doc', 'docx', 'epub', 'key', 'numbers', 'odp', 'ods', 'odt', 'pages', 'pdf', 'pps', 'ppt', 'pptx', 'rtf', 'xls', 'xlsx', 'xml', '7z', 'dmg', 'gz', 'iso', 'rar', 'tar.z', 'zip'])]),
        ),
    ]
